- docker/sds-api/integration-tests/Pipfile
- docker/sds-api/integration-tests/Pipfile.lock
- docker/sds-api/integration-tests/README.md
- docker/sds-api/integration-tests/tests/test_data/reliability_response.json
- docker/sds-api/integration-tests/tests/test_data/routing_reliability_response.json
- docker/sds-api/integration-tests/tests/test_data/routing_response.json
- docker/sds-api/integration-tests/tests/test_reliability.py
- docker/sds-api/integration-tests/tests/test_routing.py
- docker/sds-api/integration-tests/tests/test_routing_reliability.py
- docker/sds-api/integration-tests/utilities/SdsHttpRequestBuilder.py
- docker/sds-api/integration-tests/utilities/TestUtils.py
- docker/sds-api/spine-directory-service/sds/request/routing_reliability_handler.py
> NIAD-429: sds api integration tests

- specification/spine-directory.yaml
> OAS changes by Matt Lewis

- proxies/live/apiproxy/targets/ig3.xml
> NIAD 426 - connect proxy to ecs

- proxies/live/apiproxy/targets/ig3.xml
> NIAD 426 ecs proxy

- azure/azure-build-pipeline.yml
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
* :robot: Remove ref to non master branch that no longer exists
> APM-1162 Remove ref to non master utils branch

- .github/workflows/continuous-integration.yml
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
> Apm 1162 hotfix pipeline things

- azure/azure-pr-pipeline.yml
* :robot: Point to utils master
> APM-1162 Remove reference to old utils branch

- azure/project.yml
This PR looks like it does nothing, but it is used to earmark a change in azure devops.
> APM-1162 Fix release pipeline triggers

- azure/azure-release-pipeline.yml
Add short_service name to release pipeline.
> APM-1162 Add short_service_name

- azure/azure-release-pipeline.yml
> APM-1162 Use sandbox proxy for internal-qa-sandbox

- Makefile
> NIAD-426/add API-M environments

- Makefile
- azure/azure-release-pipeline.yml
- ecs-proxies-deploy-sandbox.yml
> NIAD-426 add internal-dev-sandbox env

- Makefile
- azure/azure-release-pipeline.yml
> NIAD-426 | remove internal-dev-sandbox environment

- Makefile
- scripts/deploy_proxy.sh
- scripts/deploy_spec.sh
> NIAD-429 | add OAS deployment scripts

- ecs-proxies-deploy-sandbox.yml
> NIAD-426 | Remove port from ecs proxies deploy sandbox

- specification/spine-directory.yaml
> NIAD-511 | Remove JSON endpoint and add FHIR specification to OAS3

- docker/sds-api/spine-directory-service/sds/request/http_headers.py
- docker/sds-api/spine-directory-service/sds/request/tracking_ids_headers_reader.py
> NIAD-548 check for correlation-id or x-correlation-id

- docker/sandbox/Dockerfile
> Force sandbox to run on port 9000

- docker/sandbox/Dockerfile
> NIAD-426 Undo changes to sandbox docker

- docker/sandbox/Dockerfile
> NIAD-426 | Add changes to sandbox to force port 9000

- CHANGELOG.md
> NIAD-426 add change log

- CHANGELOG.md
- docker/sandbox/stubs/__files/sds-routing-reliability-fhir-json.json
- specification/spine-directory.yaml
> Feature/NIAD-511 FHIR updates to spec and sandbox

- proxies/live/apiproxy/policies/ResponseCache.xml
> NIAD-426 Response cache settings changes

- Makefile
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- azure/project.yml
- docker/sandbox/stubs/__files/sds-routing-reliability-fhir-json.json
- scripts/deploy_spec.sh
- specification/spine-directory.yaml
> NIAD-428 Update files for OAS deployment

- .github/workflows/unit-tests.yml
- docker/sds-api/spine-directory-service/sds/Pipfile
- docker/sds-api/spine-directory-service/sds/Pipfile.lock
> Feature/niad 556 unit tests GitHub action

- azure/azure-release-pipeline.yml
> NIAD-428 | Add OAS to release pipeline

- tests/e2e/e2e.json
- tests/e2e/environments/internal-dev.postman_environment.json
- tests/e2e/environments/local.postman_environment.json
- tests/e2e/environments/postman_environment.json.template
- tests/e2e/environments/sandbox.postman_environment.json
- tests/e2e/sandbox.json
> NIAD-523 | e2e for local and internal dev

- tests/e2e/e2e.json
- tests/e2e/environments/internal-dev.postman_environment.json
- tests/e2e/environments/local.postman_environment.json
- tests/e2e/environments/postman_environment.json.template
- tests/e2e/environments/sandbox.postman_environment.json
- tests/e2e/sandbox.json
- tests/e2e/smoke.json
> NIAD-523 | update smoke tests with authentication

- CHANGELOG.md
- README.md
- docker/sandbox/stubs/mappings/endpoint-any.json
- docker/sds-api/spine-directory-service/sds/request/fhir_json_mapper.py
- docker/sds-api/spine-directory-service/sds/request/fhir_xml_mapper.py
- proxies/live/apiproxy/policies/Quota.xml
- proxies/live/apiproxy/policies/SpikeArrest.xml
- tests/e2e/e2e.json
- tests/e2e/environments/internal-dev.postman_environment.json
- tests/e2e/environments/local.postman_environment.json
- tests/e2e/environments/postman_environment.json.template
- tests/e2e/smoke.json
> NIAD 428 | OAS changes and pipeline changes

- tests/e2e/environments/internal-dev.postman_environment.json
> NIAD-428 | end to end test update

- proxies/sandbox/apiproxy/proxies/default.xml
> NIAD-428 | Change sand proxy policy to add CORS

- specification/spine-directory.yaml
> Updates to open api spec

- specification/spine-directory.yaml
> More doc changes

- ecs-proxies-deploy.yml
> NIAD-430: Using fake response for VnP testing

- ecs-proxies-deploy.yml
> NIAD-430: sds vnp config

- docker/sds-api/integration-tests/README.md
- docker/sds-api/integration-tests/tests/test_routing_reliability.py
- docker/sds-api/integration-tests/utilities/TestUtils.py
- docker/sds-api/spine-directory-service/sds/main.py
> NIAD-632: Using regex for matching routes

- specification/spine-directory.yaml
> Documentation improvements

- docker/sds-api/integration-tests/tests/test_data/routing_reliability_response.json
- docker/sds-api/integration-tests/tests/test_routing_reliability.py
- docker/sds-api/integration-tests/utilities/SdsHttpRequestBuilder.py
- docker/sds-api/integration-tests/utilities/TestUtils.py
- docker/sds-api/spine-directory-service/sds/main.py
- docker/sds-api/spine-directory-service/sds/request/content_type_validator.py
- docker/sds-api/spine-directory-service/sds/request/error_handler.py
- docker/sds-api/spine-directory-service/sds/request/http_headers.py
- docker/sds-api/spine-directory-service/sds/request/routing_reliability_handler.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_routing_reliability_handler.py
- specification/spine-directory.yaml
> NIAD-707: Returning OperationOutcome on SDS error

- specification/spine-directory.yaml
> NIAD-644-679: OAS updated

- docker/sds-api/spine-directory-service/sds/Pipfile
- docker/sds-api/spine-directory-service/sds/Pipfile.lock
- docker/sds-api/spine-directory-service/sds/utilities/integration_adaptors_logger.py
- docker/sds-api/spine-directory-service/sds/utilities/tests/test_logger.py
> NIAD-720: Logging json format

- docker/sds-api/integration-tests/utilities/SdsHttpRequestBuilder.py
- docker/sds-api/spine-directory-service/sds/request/error_handler.py
- docker/sds-api/spine-directory-service/sds/request/http_headers.py
- docker/sds-api/spine-directory-service/sds/request/tracking_ids_headers_reader.py
> NIAD-548: X-Correlation-ID for non 200 responses

- docker/sds-api/spine-directory-service/sds/request/base_handler.py
- docker/sds-api/spine-directory-service/sds/request/content_type_validator.py
- docker/sds-api/spine-directory-service/sds/request/error_handler.py
- docker/sds-api/spine-directory-service/sds/request/routing_reliability_handler.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_tracking_ids_headers_reader.py
- docker/sds-api/spine-directory-service/sds/request/tracking_ids_headers_reader.py
- docker/sds-api/spine-directory-service/sds/utilities/integration_adaptors_logger.py
- docker/sds-api/spine-directory-service/sds/utilities/mdc.py
> NIAD-749: Checking X-Correlation-ID is an UUID

- docker/sds-api/spine-directory-service/sds/request/routing_reliability_handler.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_routing_reliability_handler.py
> NIAD-548: X-Correlation-ID on 200 response header. Unit tests

- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
> NIAD-670: Remove callback requirement

- docker/sds-api/spine-directory-service/sds/request/error_handler.py
- proxies/live/apiproxy/policies/ResponseCache.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/targets/target.xml
> NIAD-768 cache policy fixes

- docker/sds-api/spine-directory-service/sds/request/error_handler.py
- proxies/live/apiproxy/policies/ResponseCache.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/targets/target.xml
> NIAD-768: cache fixes for master branch

- docker/sds-api/spine-directory-service/sds/request/content_type_validator.py
- docker/sds-api/spine-directory-service/sds/request/tests/request_handler_test_base.py
> NIAD-706: Allow multiple accept headers

- proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml
- proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml
- proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/live/apiproxy/policies/javascript.SetStatusResponse.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/resources/jsc/SetStatusResponse.js
> NIAD-695: Status endpoint on apigee

- proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml
> NIAD-785: Updated apikey source

- azure/azure-build-pipeline.yml
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
> apm-1351: use pre-release utils for aws agents

- specification/components/examples/Device.json
- specification/components/examples/DeviceBundle.json
- specification/components/examples/Endpoint.json
- specification/components/examples/EndpointBundle.json
- specification/components/schemas/Device.yaml
- specification/components/schemas/Endpoint.yaml
- specification/spine-directory.yaml
> NIAD-813: oas update

- specification/spine-directory-service.yaml
> Make a correction to a heading level in OAS spec

- docker/sds-api/spine-directory-service/sds/lookup/mock_data/sds_mhs_response.json
- docker/sds-api/spine-directory-service/sds/lookup/sds_client.py
> Niad 1183 sds gpc sandbox

- specification/spine-directory-service.yaml
> Move from Alpha to Beta

- specification/components/examples/DeviceBundle.json
- specification/components/examples/EndpointBundle.json
- specification/spine-directory-service.yaml
> NIAD-1411 correct URLs in documentation

- proxies/sandbox/apiproxy/policies/KeyValueMapOperations.GetCommonSecureVariables.xml
- proxies/sandbox/apiproxy/policies/RaiseFault.401Unauthorized.xml
- proxies/sandbox/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/sandbox/apiproxy/policies/javascript.SetStatusResponse.xml
- proxies/sandbox/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/resources/jsc/SetStatusResponse.js
> NIAD-1422: Status endpoint for sandbox

- docker/sds-api/spine-directory-service/sds/lookup/sds_client.py
> NIAD-1458: Sandbox fix

- specification/spine-directory-service.yaml
> NIAD-1458: Documentation update

- Makefile
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- azure/components/run-security-tests.yml
- azure/components/run-smoke-tests.yml
- azure/templates/run-tests.yml
- pytest.ini
- tests/api_tests.py
> NIAD-1458: enable e2e tests for sandbox

- azure/azure-release-pipeline.yml
> NIAD-1458: Run only smoke tests on release

- specification/spine-directory-service.yaml
> NIAD-1458: Examples updated

- docker/sds-api/spine-directory-service/running-sds-adaptor-locally.md
- docker/sds-api/spine-directory-service/sds/lookup/sds_client.py
- docker/sds-api/spine-directory-service/sds/main.py
- docker/sds-api/spine-directory-service/sds/request/healthcheck_handler.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_healthcheck_handler.py
- proxies/live/apiproxy/policies/ResponseCache.xml
- proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/sandbox/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- tests/api_tests.py
> NIAD-1292: Healthcheck update

- docker/sds-api/spine-directory-service/sds/request/healthcheck_handler.py
- tests/api_tests.py
> NIAD-1292: Fixed deep healthcheck for sandbox where there is no SDS url

- Makefile
- azure/azure-build-pipeline.yml
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- docker/sds-api/spine-directory-service/sds/request/healthcheck_handler.py
- ecs-proxies-deploy-prod.yml
- ecs-proxies-deploy.yml
- manifest_template.yml
- proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/sandbox/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- tests/api_tests.py
> apm-2214: go live checklist review suggestions

- ecs-proxies-deploy-prod.yml
- ecs-proxies-deploy.yml
> mm: sds root ca cert missing /crt suffix

- specification/spine-directory-service.yaml
> NIAD-1477 portal documentation update

- manifest_template.yml
- specification/spine-directory-service.yaml
> NIAD-1620: Documentation updated

- specification/spine-directory-service.yaml
> NIAD-1611: Add information on apikey authentication

- proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
> NIAD-1611 CORS fix

- specification/spine-directory-service.yaml
> NIAD-1611 remove UUID format from apikey

- specification/spine-directory-service.yaml
> NIAD-1620: Removed incorrect onboarding instruction

- docker/sds-api/spine-directory-service/sds/lookup/mock_data/sds_as_response.json
- docker/sds-api/spine-directory-service/sds/lookup/mock_data/sds_mhs_response.json
- docker/sds-api/spine-directory-service/sds/request/fhir_json_mapper.py
> NIAD-1634: Lower case access key. MHS test data

- docker/sds-api/spine-directory-service/sds/request/fhir_json_mapper.py
> NIAD-1634: Null safety

- docker/sds-api/spine-directory-service/sds/request/fhir_json_mapper.py
> NIAD-1634 sds sandbox test data for mhs int tests

- docker/sds-api/spine-directory-service/sds/lookup/sds_client.py
- docker/sds-api/spine-directory-service/sds/request/fhir_json_mapper.py
> NIAD-1634: Bug fix where LDAP already returns a case insensitive dict

- .github/workflows/unit-tests.yml
- specification/spine-directory-service.yaml
> NIAD-1891 production URL added to doc

- docker/sds-api/spine-directory-service/sds/lookup/mock_data/sds_as_response.json
- docker/sds-api/spine-directory-service/sds/lookup/sds_client.py
- docker/sds-api/spine-directory-service/sds/lookup/tests/data/my_real_server_entries.json
- docker/sds-api/spine-directory-service/sds/lookup/tests/data/my_real_server_schema.json
- docker/sds-api/spine-directory-service/sds/request/fhir_json_mapper.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_accredited_system_handler.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_data/fhir_json_mapper/device/everything.in.json
> NIAD-1936: fix incorrect manufacturer mapping in Device resource

- proxies/live/apiproxy/policies/ResponseCache.xml
> NIAD-1955 increase cache TTL to 30 minutes

- specification/spine-directory-service.yaml
> NIAD-2012 SDS sandbox query params examples

- Makefile
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- ecs-proxies-deploy-dep.yml
- manifest_template.yml
- proxies/sandbox/apiproxy/resources/jsc/SetStatusResponse.js
https://nhsd-jira.digital.nhs.uk/browse/APM-3252
> APM-3252 configure dep

- specification/spine-directory-service.yaml
> APM-000 AMP-941 API Specs - add Errors section

- .github/workflows/continuous-integration.yml
- .github/workflows/pr-lint.yaml
- manifest_template.yml
part of the process of moving identify provider from nhs-id to nhs-cis2
> AMB-1179 added cis2 scope to manifest

- README.md
> APM-0000 Artbitrary change to check merge trigger

- docker/sds-api/integration-tests/README.md
- docker/sds-api/spine-directory-service/running-sds-adaptor-locally.md
- docker/sds-api/spine-directory-service/sds-adaptor-dev-notes.md
[DO NOT MERGE] - this is a test build
> NIAD-9999 Allow BAU tickets to build

- docker/sds-api/spine-directory-service/sds/request/accredited_system_handler.py
- docker/sds-api/spine-directory-service/sds/request/base_handler.py
- docker/sds-api/spine-directory-service/sds/request/cpm.py
> [feature/PI-231] Filter for CPM on Devices

- docker/sds-api/spine-directory-service/sds/request/routing_reliability_handler.py
> [feature/PI-233] Filter for CPM on Endpoints

- .github/workflows/pr-lint.yaml
- CHANGELOG.md
- docker/sds-api/spine-directory-service/sds/request/accredited_system_handler.py
- docker/sds-api/spine-directory-service/sds/request/base_handler.py
- docker/sds-api/spine-directory-service/sds/request/cpm.py
- docker/sds-api/spine-directory-service/sds/request/routing_reliability_handler.py
> Release 2024-02-09

- docker/sds-api/spine-directory-service/sds/request/cpm.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_data/cpm/filtered_device.json
- docker/sds-api/spine-directory-service/sds/request/tests/test_data/cpm/filtered_device2.json
- docker/sds-api/spine-directory-service/sds/request/tests/test_data/cpm/filtered_devices.json
- docker/sds-api/spine-directory-service/sds/request/tests/test_data/cpm/returned_devices.json
> [feature/PI-238] Filter and translate CPM data (Device)

- azure/azure-release-pipeline.yml
> [feature/PI-259] Add prod producer approval

- .vscode/launch.json
- CHANGELOG.md
- Makefile
- docker/sds-api/spine-directory-service/sds/Pipfile
- docker/sds-api/spine-directory-service/sds/Pipfile.lock
- docker/sds-api/spine-directory-service/sds/request/accredited_system_handler.py
- docker/sds-api/spine-directory-service/sds/request/cpm.py
- docker/sds-api/spine-directory-service/sds/request/cpm_config.py
- docker/sds-api/spine-directory-service/sds/request/fhir_json_mapper.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_devices.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_data/cpm/schema.py
- ecs-proxies-deploy-dep.yml
- ecs-proxies-deploy-int.yml
- ecs-proxies-deploy-internal-dev-sandbox.yml
- ecs-proxies-deploy-internal-dev.yml
- ecs-proxies-deploy-internal-qa-sandbox.yml
- ecs-proxies-deploy-internal-qa.yml
- ecs-proxies-deploy-prod.yml
- ecs-proxies-deploy-ref.yml
- ecs-proxies-deploy-sandbox.yml
- ecs-proxies-deploy.yml
- tests/api_tests.py
> Release 2023-03-13

- ecs-proxies-deploy-dep.yml
- ecs-proxies-deploy-int.yml
- ecs-proxies-deploy-internal-dev-sandbox.yml
- ecs-proxies-deploy-internal-dev.yml
- ecs-proxies-deploy-internal-qa-sandbox.yml
- ecs-proxies-deploy-internal-qa.yml
- ecs-proxies-deploy-ref.yml
- ecs-proxies-deploy-sandbox.yml
- ecs-proxies-deploy.yml
> [feature/PI-275] Use param store for cpm apikey

- docker/sds-api/spine-directory-service/sds/request/cpm.py
- ecs-proxies-deploy-int.yml
> Use ptl for int

- ecs-proxies-deploy-sandbox.yml
> Add sandbox

- docker/sds-api/spine-directory-service/sds/request/cpm.py
> [feature/PI-268-Search_for_a_device] Use mock query_param to return mocked version

- azure/azure-pr-pipeline.yml
- ecs-proxies-deploy-int.yml
- ecs-proxies-deploy-ref.yml
- ecs-proxies-deploy.yml
> APM-5356 update ldap secret paths to new certs

- azure/azure-release-pipeline.yml
- ecs-proxies-deploy-prod.yml
- tests/api_tests.py
> APM-5356 update prod secret paths for sds key and certs

- docker/sds-api/spine-directory-service/sds/Pipfile
- docker/sds-api/spine-directory-service/sds/Pipfile.lock
- docker/sds-api/spine-directory-service/sds/request/accredited_system_handler.py
- docker/sds-api/spine-directory-service/sds/request/base_handler.py
- docker/sds-api/spine-directory-service/sds/request/cpm.py
- docker/sds-api/spine-directory-service/sds/request/routing_reliability_handler.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_config.py
- ecs-proxies-deploy-dep.yml
- ecs-proxies-deploy-int.yml
- ecs-proxies-deploy-internal-dev-sandbox.yml
- ecs-proxies-deploy-internal-dev.yml
- ecs-proxies-deploy-internal-qa-sandbox.yml
- ecs-proxies-deploy-internal-qa.yml
- ecs-proxies-deploy-prod.yml
- ecs-proxies-deploy-ref.yml
- ecs-proxies-deploy-sandbox.yml
- ecs-proxies-deploy.yml
> [PI-453] USE_CPM external toggle

- .vscode/launch.json
- CHANGELOG.md
- README.md
- docker/sds-api/spine-directory-service/sds/Pipfile
- docker/sds-api/spine-directory-service/sds/Pipfile.lock
- docker/sds-api/spine-directory-service/sds/request/accredited_system_handler.py
- docker/sds-api/spine-directory-service/sds/request/base_handler.py
- docker/sds-api/spine-directory-service/sds/request/cpm.py
- docker/sds-api/spine-directory-service/sds/request/routing_reliability_handler.py
- docker/sds-api/spine-directory-service/sds/request/tests/request_handler_test_base.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_accredited_system_handler.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_config.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_routing_reliability_handler.py
- ecs-proxies-deploy-dep.yml
- ecs-proxies-deploy-int.yml
- ecs-proxies-deploy-internal-dev-sandbox.yml
- ecs-proxies-deploy-internal-dev.yml
- ecs-proxies-deploy-internal-qa-sandbox.yml
- ecs-proxies-deploy-internal-qa.yml
- ecs-proxies-deploy-prod.yml
- ecs-proxies-deploy-ref.yml
- ecs-proxies-deploy-sandbox.yml
- ecs-proxies-deploy.yml
> Release 2024-07-18

- ecs-proxies-deploy-prod.yml
> [Feature PI-313] - Add prod cpm apikey

- docker/sds-api/spine-directory-service/sds/request/cpm.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_devices.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_endpoints.py
> [feature/PI-489] Strip whitespace from incoming query params

- CHANGELOG.md
- docker/sds-api/spine-directory-service/sds/request/cpm.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_devices.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_endpoints.py
> Release 2024-09-02

- docker/sds-api/spine-directory-service/sds/request/cpm.py
> [feature/PI-356] Missing await

- README.md
- docker/sds-api/spine-directory-service/sds/request/cpm_config.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_devices.py
> [feature/PI-672] Change nhs_as_client cpm param to nhs_id_code

- CHANGELOG.md
- README.md
- docker/sds-api/spine-directory-service/sds/request/cpm_config.py
- docker/sds-api/spine-directory-service/sds/request/tests/test_cpm_devices.py
> Release 2025-01-07
